# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-09 11:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InstagramAccounts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('instagram_username', models.CharField(max_length=50)),
                ('instagram_password', models.CharField(max_length=50)),
                ('instagram_image', models.CharField(max_length=50)),
                ('instagram_account_status', models.CharField(max_length=50)),
                ('paid_date', models.CharField(max_length=50)),
            ],
        ),
    ]
