# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-09 13:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Insta_Web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instagramaccounts',
            name='instagram_password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
    ]
