# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-09 14:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Insta_Web', '0002_auto_20171109_1305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instagramaccounts',
            name='instagram_account_status',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='instagramaccounts',
            name='instagram_image',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='instagramaccounts',
            name='instagram_password',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='instagramaccounts',
            name='instagram_username',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='instagramaccounts',
            name='paid_date',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='instagramaccounts',
            name='username',
            field=models.CharField(max_length=128),
        ),
    ]
