# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-12 13:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Insta_Web', '0003_auto_20171109_1452'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstagramTargetDatabase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=128)),
                ('instagram_username', models.CharField(max_length=128)),
                ('target', models.CharField(max_length=128)),
                ('target_value', models.CharField(max_length=256)),
                ('pid', models.CharField(max_length=128)),
            ],
        ),
    ]
