# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-12 13:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Insta_Web', '0004_instagramtargetdatabase'),
    ]

    operations = [
        migrations.AddField(
            model_name='instagramtargetdatabase',
            name='status',
            field=models.CharField(default=django.utils.timezone.now, max_length=128),
            preserve_default=False,
        ),
    ]
