# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-12 14:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Insta_Web', '0005_instagramtargetdatabase_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='instagramtargetdatabase',
            name='delete_link',
            field=models.CharField(default='link', max_length=500),
        ),
        migrations.AddField(
            model_name='instagramtargetdatabase',
            name='pause_play_link',
            field=models.CharField(default='link', max_length=500),
        ),
    ]
