# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-12 15:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Insta_Web', '0006_auto_20171112_1421'),
    ]

    operations = [
        migrations.RenameField(
            model_name='instagramtargetdatabase',
            old_name='delete_link',
            new_name='link_id',
        ),
        migrations.RemoveField(
            model_name='instagramtargetdatabase',
            name='pause_play_link',
        ),
    ]
