# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-12 16:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Insta_Web', '0007_auto_20171112_1523'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instagramtargetdatabase',
            name='link_id',
        ),
    ]
