# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-12 16:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Insta_Web', '0008_remove_instagramtargetdatabase_link_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='instagramtargetdatabase',
            name='link_id',
            field=models.CharField(default='default', max_length=500),
        ),
    ]
