# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-17 11:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Insta_Web', '0009_instagramtargetdatabase_link_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instagramtargetdatabase',
            name='target',
        ),
    ]
