# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-19 12:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Insta_Web', '0012_auto_20171119_1211'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instagramtargetdatabase',
            name='followers_usernameids',
        ),
        migrations.RemoveField(
            model_name='instagramtargetdatabase',
            name='following_mediaids',
        ),
    ]
