# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-23 18:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Insta_Web', '0015_auto_20171119_1526'),
    ]

    operations = [
        migrations.AddField(
            model_name='instagramtargetdatabase',
            name='pause_follow',
            field=models.CharField(default='True', max_length=20),
        ),
        migrations.AddField(
            model_name='instagramtargetdatabase',
            name='pause_like',
            field=models.CharField(default='True', max_length=20),
        ),
    ]
