# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-26 17:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Insta_Web', '0016_auto_20171123_1846'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InstagramTargetDatabase',
        ),
    ]
