# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-26 17:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Insta_Web', '0017_delete_instagramtargetdatabase'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=128)),
                ('instagram_username', models.CharField(max_length=128)),
                ('target', models.CharField(default='None', max_length=128)),
                ('target_value', models.CharField(max_length=256)),
                ('following', models.CharField(max_length=100)),
                ('likes', models.CharField(max_length=100)),
                ('message', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TargetFunctionalityDB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=128)),
                ('instagram_username', models.CharField(max_length=128)),
                ('target', models.CharField(default='None', max_length=128)),
                ('target_value', models.CharField(max_length=256)),
                ('following_mediaids', models.CharField(default=0, max_length=256)),
                ('followers_usernameids', models.CharField(default=0, max_length=256)),
                ('pid', models.CharField(max_length=128)),
                ('status', models.CharField(max_length=128)),
                ('link_id', models.CharField(default='default', max_length=500)),
                ('pause_follow', models.CharField(default='True', max_length=20)),
                ('pause_like', models.CharField(default='True', max_length=20)),
            ],
        ),
    ]
