# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-26 17:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Insta_Web', '0018_accountdetails_targetfunctionalitydb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountdetails',
            name='following',
            field=models.CharField(default='0', max_length=100),
        ),
        migrations.AlterField(
            model_name='accountdetails',
            name='likes',
            field=models.CharField(default='0', max_length=100),
        ),
        migrations.AlterField(
            model_name='accountdetails',
            name='message',
            field=models.CharField(default='0', max_length=100),
        ),
    ]
