# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-27 11:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Insta_Web', '0019_auto_20171126_1745'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageFunctionalityDB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.CharField(default='default', max_length=500)),
                ('username', models.CharField(max_length=128)),
                ('instagram_username', models.CharField(max_length=128)),
                ('pause_message', models.CharField(default='True', max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='accountdetails',
            name='message',
        ),
        migrations.RemoveField(
            model_name='accountdetails',
            name='target',
        ),
        migrations.RemoveField(
            model_name='accountdetails',
            name='target_value',
        ),
        migrations.AddField(
            model_name='accountdetails',
            name='messages_sent',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='accountdetails',
            name='following',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='accountdetails',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
