# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-28 11:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Insta_Web', '0020_auto_20171127_1152'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagefunctionalitydb',
            name='messages_sent',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='messagefunctionalitydb',
            name='pid',
            field=models.CharField(default=None, max_length=128),
        ),
        migrations.AddField(
            model_name='messagefunctionalitydb',
            name='status',
            field=models.CharField(default='pause', max_length=20),
        ),
    ]
