# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-28 12:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Insta_Web', '0021_auto_20171128_1139'),
    ]

    operations = [
        migrations.RenameField(
            model_name='messagefunctionalitydb',
            old_name='pause_message',
            new_name='message_pause',
        ),
    ]
