# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-30 12:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Insta_Web', '0022_auto_20171128_1210'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstagramUnfollowDB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=128)),
                ('instagram_username', models.CharField(max_length=128)),
                ('cleanup_pause', models.CharField(max_length=20)),
                ('unfollow_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='accountdetails',
            name='unfollow_count',
            field=models.IntegerField(default=0),
        ),
    ]
