# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-01 19:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Insta_Web', '0023_auto_20171130_1217'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountdetails',
            name='pid',
            field=models.CharField(default=None, max_length=128),
        ),
    ]
